"""empty message

Revision ID: 20727cb3b8bb
Revises: 4366fa7692d4
Create Date: 2023-12-15 10:58:51.511513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20727cb3b8bb'
down_revision = '4366fa7692d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('regular_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regular_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
