"""empty message

Revision ID: 4366fa7692d4
Revises: bcc3053390d2
Create Date: 2023-12-11 11:42:28.518653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4366fa7692d4'
down_revision = 'bcc3053390d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('item_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_value', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('total_value')

    # ### end Alembic commands ###
