"""empty message

Revision ID: 68e00ff3b382
Revises: 77b39d1a7128
Create Date: 2023-10-17 09:51:40.455778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68e00ff3b382'
down_revision = '77b39d1a7128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
