"""empty message

Revision ID: b96c3c3e57dd
Revises: d2ac6fbfcc13
Create Date: 2023-11-13 18:02:03.100302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96c3c3e57dd'
down_revision = 'd2ac6fbfcc13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
