"""empty message

Revision ID: bcc3053390d2
Revises: 
Create Date: 2023-12-07 11:56:19.911114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcc3053390d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_value', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('cart_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_value', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('item_value')

    # ### end Alembic commands ###
